[workspace]

members = [
    "d1",
    "d2",
    "d3",
    "common",
    "d4",
    "d5",
    "d6",
    "d9",
    "d7",
    "d8",
    "d10",
    "d11",
    "d12",
    "d13",
    "d14",
    "d15",
    "vec2d",
    "d16",
    "d17",
    "d18",
    "d19",
    "d20",
]
