[package]
name = "d19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
text_io = "0.1.9"
ndarray = "0.15.4"
lazy_static = "1.4.0"
# ndarray-linalg = "0.14.1"