name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install bazelisk
      run: |
        wget https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64
        chmod +x ./bazelisk-linux-amd64
    - name: Build projects
      run: ./bazelisk-linux-amd64 build -c opt //cpp:all
