name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
# Exclude d19v2 which depends on a working BLAS, which I don't want to figure
# out on github
    - name: Build
      run: cargo build --verbose --workspace --exclude d19v2
    - name: Run tests
      run: cargo test --verbose --workspace --exclude d19v2
